---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rgee)
library(sf)
ee_Initialize()
# ee_reattach() # reattach ee as a reserve word
```

Define the regional bounds of animation frames and a mask to clip the NDVI data by.

``` {r}
mask <- st_read(here::here("data/lower_cb_poly.kml")) %>% 
  sf::st_zm() %>% 
  st_transform(., crs = crs("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")) %>% 
  sf_as_ee()

region <- mask$geometry()$bounds()
```

Retrieve the MODIS Terra Vegetation Indices 16-Day Global 1km dataset as an `ee.ImageCollection`
and select the NDVI band.

```{r}
# col <- ee$ImageCollection('MODIS/006/MOD13A2')$select('NDVI')
col <- ee$ImageCollection("NASA/OCEANDATA/MODIS-Terra/L3SMI")$
  filterBounds(ee$Geometry$Point(c(-76.377094, 37.198504)))$
  filterDate('2017-01-01', '2017-02-01')
  # filter(ee$Filter$listContains("system:band_names", "N"))

ee_crs <- col$first()$projection()$getInfo()$crs

## Using drive
ic_drive_files <- ee_imagecollection_to_local(
  ic = col,
  region = region,
  dsn = file.path(here::here("data"), "drive_")
)

t <- stack(here::here("data/drive__T2017004.tif"))
plot(t)
unique(values(t))
# USDA example
loc <- ee$Geometry$Point(-99.2222, 46.7816)
collection <- ee$ImageCollection('USDA/NAIP/DOQQ')$
  filterBounds(loc)$
  filterDate('2008-01-01', '2020-01-01')$
  filter(ee$Filter$listContains("system:band_names", "N"))

# From ImageCollection to local directory
ee_crs <- collection$first()$projection()$getInfo()$crs
geometry <- collection$first()$geometry(proj = ee_crs)$bounds()
tmp <- tempdir()

## Using drive
ic_drive_files <- ee_imagecollection_to_local(
  ic = collection,
  region = geometry,
  scale = 100,
  dsn = file.path(here::here("data"), "drive_")
)

t <- raster(here::here("data/drive__m_4609915_sw_14_1_20090818.tif"))
plot(t)
```